=== cmoyates/phon/ipa/src/main/resources/xml/xsd/features.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
   Phon - An open source tool for research in phonology.
   Copyright (C) 2018 Gregory Hedlund & Yvan Rose
    
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<!--
    This file specifies the xml file format for Phon's feature matrix.
    Feature sets are used in many of the internal algorithms and searches
    in Phon.
    
    For more information on creating custom feature sets for use in searches,
    see http://phon.ling.mun.ca/phontrac/wiki/search/customfeatures
-->
<!-- 
    2012-01-11 (gjh): created file
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="https://phon.ca/ns/features"
    targetNamespace="https://phon.ca/ns/features">
    
    <!--
        Our root element
    -->
    <xs:element name="feature_matrix" type="featureMatrixType">
        <!--
            Setup constraints for references to
            declared features
        -->
        <xs:key name="feature_key">
            <xs:selector xpath="feature"></xs:selector>
            <xs:field xpath="@name"></xs:field>
        </xs:key>
        
        <xs:keyref refer="feature_key" name="feature_key_ref">
            <xs:selector xpath="."></xs:selector>
            <xs:field xpath="feature_set"></xs:field>
        </xs:keyref>
        
        <xs:keyref refer="feature_key" name="named_feature_key_ref">
            <xs:selector xpath="."></xs:selector>
            <xs:field xpath="named_feature_set"></xs:field>
        </xs:keyref>
        
        <!--
            Don't allow duplicate unicode entries
        -->
        <xs:unique name="feature_set_key">
            <xs:selector xpath=".//feature_set"></xs:selector>
            <xs:field xpath="@char"></xs:field>
        </xs:unique>
        
        <xs:unique name="named_feature_set_key">
            <xs:selector xpath=".//named_feature_set"></xs:selector>
            <xs:field xpath="@name"></xs:field>
        </xs:unique>
    </xs:element>
    
    <!--
        JAXB requires elements we wish to parse in fragments 
        to be declared at the root level of the schema
    -->
    <xs:element name="feature" type="featureType"/>
    <xs:element name="named_feature_set" type="namedFeatureSetType"/>
    <xs:element name="feature_set" type="featureSetType"/>
    <xs:element name="features" type="xs:IDREFS"/>
    <xs:element name="name" type="nonEmptyString"/>
    <xs:element name="synonym" type="nonEmptyString"/>
    <xs:element name="primary_family" type="family"/>
    <xs:element name="secondary_family" type="family"/>
    
    <xs:complexType name="featureMatrixType" mixed="false">
        <xs:sequence>
            <xs:element ref="feature" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="named_feature_set" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="feature_set" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="namedFeatureSetType" mixed="false">
        <xs:simpleContent>
            <xs:extension base="xs:IDREFS">
                <xs:attribute name="name" type="nonEmptyString" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="featureSetType" mixed="false">
        <xs:simpleContent>
            <xs:extension base="xs:IDREFS">
                <xs:attribute name="char" type="singleChar" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="featureType" mixed="false">
        <xs:sequence>
            <xs:element ref="synonym" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="primary_family" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="secondary_family" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        
        <xs:attribute name="name" type="xs:ID" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="family">
        <xs:restriction base="xs:string">
            <xs:enumeration value="place"/>
            <xs:enumeration value="manner"/>
            <xs:enumeration value="height"/>
            <xs:enumeration value="tongue root"/>
            <xs:enumeration value="backness"/>
            <xs:enumeration value="diacritic"/>
            <xs:enumeration value="labial"/>
            <xs:enumeration value="dorsal"/>
            <xs:enumeration value="coronal"/>
            <xs:enumeration value="voicing"/>
            <xs:enumeration value="continuancy"/>
            <xs:enumeration value="nasality"/>
            <xs:enumeration value="stridency"/>
            <xs:enumeration value="guttural"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="singleChar">
        <xs:restriction base="xs:string">
            <xs:length value="1"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== cmoyates/phon/ipa/src/main/resources/ca/phon/ipa/features/features.xml
<?xml version="1.0" encoding="UTF-8"?>
<feature_matrix xmlns="https://phon.ca/ns/features"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="https://phon.ca/ns/features ../../../../xml/xsd/features.xsd">
	<feature name="null"/>
	<feature name="diacritic"/>
	<feature name="unintelligible"/>
	<feature name="unreleased">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="consonant">
		<synonym>c</synonym>
	</feature>
	<feature name="vowel">
		<synonym>v</synonym>
	</feature>
	<feature name="glide">
		<synonym>g</synonym>
	</feature>
	<feature name="cover"/>
	<feature name="schwa">
		<synonym>sch</synonym>
	</feature>
	<feature name="labial">
		<synonym>lab</synonym>
		<primary_family>place</primary_family>
		<secondary_family>labial</secondary_family>
	</feature>
	<feature name="bilabial">
		<synonym>bil</synonym>
		<primary_family>place</primary_family>
		<secondary_family>labial</secondary_family>
	</feature>
	<feature name="round">
		<primary_family>place</primary_family>
		<secondary_family>labial</secondary_family>
	</feature>
	<feature name="palatal">
		<synonym>pal</synonym>
		<primary_family>place</primary_family>
		<secondary_family>dorsal</secondary_family>
	</feature>
	<feature name="dorsal">
		<synonym>dor</synonym>
		<primary_family>place</primary_family>
		<secondary_family>dorsal</secondary_family>
	</feature>
	<feature name="velar">
		<synonym>vel</synonym>
		<primary_family>place</primary_family>
		<secondary_family>dorsal</secondary_family>
	</feature>
	<feature name="uvular">
		<synonym>uvu</synonym>
		<primary_family>place</primary_family>
		<secondary_family>dorsal</secondary_family>
	</feature>
	<feature name="guttural">
		<synonym>gut</synonym>
		<primary_family>place</primary_family>
		<secondary_family>guttural</secondary_family>
	</feature>
	<feature name="pharyngeal">
		<synonym>pha</synonym>
		<primary_family>place</primary_family>
		<secondary_family>guttural</secondary_family>
	</feature>
	<feature name="laryngeal">
		<synonym>lar</synonym>
		<synonym>glottal</synonym>
		<primary_family>place</primary_family>
		<secondary_family>guttural</secondary_family>
	</feature>
	<feature name="epiglottal">
		<synonym>epi</synonym>
		<primary_family>place</primary_family>
		<secondary_family>guttural</secondary_family>
	</feature>
	<feature name="dental">
		<synonym>den</synonym>
		<primary_family>place</primary_family>
		<secondary_family>coronal</secondary_family>
	</feature>
	<feature name="apical">
		<synonym>api</synonym>
		<primary_family>place</primary_family>
		<secondary_family>coronal</secondary_family>
	</feature>
	<feature name="laminal">
		<synonym>lam</synonym>
		<primary_family>place</primary_family>
		<secondary_family>coronal</secondary_family>
	</feature>
	<feature name="coronal">
		<synonym>cor</synonym>
		<primary_family>place</primary_family>
		<secondary_family>coronal</secondary_family>
	</feature>
	<feature name="lingual">
		<synonym>lin</synonym>
		<primary_family>place</primary_family>
	</feature>
	<feature name="anterior">
		<synonym>ant</synonym>
		<primary_family>place</primary_family>
		<secondary_family>coronal</secondary_family>
	</feature>
	<feature name="posterior">
		<synonym>pos</synonym>
		<primary_family>place</primary_family>
		<secondary_family>coronal</secondary_family>
	</feature>
	<feature name="alveolar">
		<synonym>alv</synonym>
		<primary_family>place</primary_family>
		<secondary_family>coronal</secondary_family>
	</feature>
	<feature name="alveopalatal">
		<synonym>alp</synonym>
		<synonym>postalveolar</synonym>
		<primary_family>place</primary_family>
		<secondary_family>coronal</secondary_family>
	</feature>
	<feature name="retroflex">
		<primary_family>place</primary_family>
		<secondary_family>coronal</secondary_family>
	</feature>
	<feature name="distributed">
		<synonym>dis</synonym>
		<primary_family>place</primary_family>
		<secondary_family>coronal</secondary_family>
	</feature>
	<feature name="voiceless">
		<synonym>vcl</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>voicing</secondary_family>
	</feature>
	<feature name="voiced">
		<synonym>vcd</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>voicing</secondary_family>
	</feature>
	<feature name="aspirated">
		<primary_family>manner</primary_family>
		<secondary_family>voicing</secondary_family>
	</feature>
	<feature name="weaklyaspirated">
		<primary_family>manner</primary_family>
		<secondary_family>voicing</secondary_family>
	</feature>
	<feature name="unaspirated">
		<primary_family>manner</primary_family>
		<secondary_family>voicing</secondary_family>
	</feature>
	<feature name="approximant">
		<synonym>app</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="liquid">
		<synonym>liq</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="lateral">
		<synonym>lat</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="rhotic">
		<synonym>rho</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="stop">
		<synonym>plosive</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="continuant">
		<synonym>cnt</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="obstruent">
		<synonym>obs</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="sonorant">
		<synonym>son</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="fricative">
		<synonym>fri</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="affricate">
		<synonym>aff</synonym>
		<synonym>delayedrelease</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="click">
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="implosive">
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="flap">
		<synonym>tap</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="trill">
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="ejective">
		<primary_family>manner</primary_family>
		<secondary_family>continuancy</secondary_family>
	</feature>
	<feature name="nasal">
		<synonym>nas</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>nasality</secondary_family>
	</feature>
	<feature name="prenasalized">
		<primary_family>manner</primary_family>
		<secondary_family>nasality</secondary_family>
	</feature>
	<feature name="strident">
		<synonym>str</synonym>
		<primary_family>manner</primary_family>
		<secondary_family>stridency</secondary_family>
	</feature>
	<feature name="low">
		<primary_family>height</primary_family>
	</feature>
	<feature name="mid">
		<primary_family>height</primary_family>
	</feature>
	<feature name="high">
		<primary_family>height</primary_family>
	</feature>
	<feature name="tense">
		<primary_family>tongue root</primary_family>
	</feature>
	<feature name="atr">
		<primary_family>tongue root</primary_family>
	</feature>
	<feature name="rtr">
		<primary_family>tongue root</primary_family>
	</feature>
	<feature name="lax">
		<primary_family>tongue root</primary_family>
	</feature>
	<feature name="front">
		<primary_family>backness</primary_family>
	</feature>
	<feature name="central">
		<primary_family>backness</primary_family>
	</feature>
	<feature name="back">
		<primary_family>backness</primary_family>
	</feature>
	<feature name="syllabic">
		<synonym>syl</synonym>
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="nonsyllabic">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="advanced">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="retracted">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="lowered">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="raised">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="fronted">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="backed">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="morerounded">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="lessrounded">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="long">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="halflong">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="extrashort">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="breathyvoiced">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="creakyvoiced">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="prstress">
		<synonym>1</synonym>
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="secstress">
		<synonym>2</synonym>
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="toneglobalrise">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="tonedownstep">
		<primary_family>diacritic</primary_family>
	</feature>
	<feature name="tonefalling">
		<primary_family>diacritic</primary_family>
	</feature>
