=== cmoyates/phon/syllabifier/src/main/resources/xml/xsd/syllabifier.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Phon - An open source tool for research in phonology.
 Copyright (C) 2008 The Phon Project, Memorial University <http://phon.ling.mun.ca>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns="https://www.phon.ca/ns/syllabifier" targetNamespace="https://www.phon.ca/ns/syllabifier"
    version="2.0">
    
    <xs:annotation>
        <xs:documentation> This document describes the structure of the Phon ca.phon.syllabifier.basic.BasicSyllabifier definition
            files. Author: Greg J. Hedlund &lt;ghedlund@cs.mun.ca&gt; (C) 2006-2007 The Phon
            Project </xs:documentation>
    </xs:annotation>

    <xs:element name="SyllabifierDef">
        <xs:annotation>
            <xs:documentation> The syllabifier definition. </xs:documentation>
        </xs:annotation>

        <xs:complexType mixed="false">
            <xs:sequence>

                <!-- Sonority Scale -->
                <xs:element name="SonorityScale" type="SonorityValues" maxOccurs="1" minOccurs="1"/>

                <!-- Steps -->
                <xs:element name="Stage" minOccurs="0" maxOccurs="unbounded" type="StageType"/>

            </xs:sequence>

            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="language" type="xs:language" use="required"/>
        </xs:complexType>

    </xs:element>
    
    <xs:complexType name="StageType" mixed="false">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="exprs" type="PhonexList"/>
            <xs:element name="map" type="TypeMap"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="continueUntilFail" type="xs:boolean" default="false"/>
    </xs:complexType>
    
    <xs:complexType name="SonorityValues" mixed="false">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="SonorityClass">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="exprs" type="PhonexList"/>
                        <xs:element name="sonorityValue" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="SonorityDirection">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Right"/>
            <xs:enumeration value="Left"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="PhonexList">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="phonex" type="nonEmptyString"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="TypeMap">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="set" type="MarkGroup"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="MarkGroup">
        <xs:attribute name="group" type="nonEmptyString" use="required"/>
        <xs:attribute name="mark" type="ConstituentType" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="ConstituentType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Left Appendix"/>
            <xs:enumeration value="Onset"/>
            <xs:enumeration value="Nucleus"/>
            <xs:enumeration value="Coda"/>
            <xs:enumeration value="Right Appendix"/>
            <xs:enumeration value="OEHS"/>
            <xs:enumeration value="Ambisyllabic"/>
            <xs:enumeration value="Diphthong"/>
            <xs:enumeration value="Unknown"/>
            <xs:enumeration value="Don't Care"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== cmoyates/phon/syllabifier/src/main/resources/syllabifier/basic/cre.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Phon - An open source tool for research in phonology.
 Copyright (C) 2008 The Phon Project, Memorial University <http://phon.ling.mun.ca>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<SyllabifierDef xmlns="https://www.phon.ca/ns/syllabifier"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.phon.ca/ns/syllabifier ../../xml/xsd/syllabifier.xsd"
    name="Cree" language="cre">
    
    <SonorityScale>
        <SonorityClass>
            <phonex>{obs,-uvular,-fri}</phonex>
            <sonorityValue>0</sonorityValue>
        </SonorityClass>
        
        <SonorityClass>
            <phonex>{c, nas}</phonex>
            <sonorityValue>1</sonorityValue>
        </SonorityClass>
        
        <SonorityClass>
            <phonex>[{liq}{uvular,fri}]</phonex>
            <sonorityValue>2</sonorityValue>
        </SonorityClass>
        
        <SonorityClass>
            <phonex>\g</phonex>
            <sonorityValue>3</sonorityValue>
        </SonorityClass>
        
        <SonorityClass>
            <phonex>\v</phonex>
            <sonorityValue>4</sonorityValue>
        </SonorityClass>
    </SonorityScale>
    
    <Stage name="MarkNuclei">
        <phonex>(D=\v[\g{v,high,lax}])</phonex>
        <phonex>(N=\v)</phonex>
        <group name="D" mark="Diphthong"/>
        <group name="N" mark="Nucleus"/>
    </Stage>
    
    <Stage name="MarkFinalConsonant">
        <phonex>(E=\c)$</phonex>
        <group name="E" mark="OEHS"/>
    </Stage>

    <Stage name="FixFinalCodas">
        <phonex>(C=[{-v,laryngeal}{-v,nas}{-v,fri,cor}]:OEHS)</phonex>
        <group name="C" mark="Coda"/>
    </Stage>
    
    <Stage name="MaxOEHS">
        <phonex>(E=\c).:OEHS:mdc("2","false")</phonex>
        <group name="E" mark="OEHS"/>
    </Stage>
    
    <Stage name="MarkOnset">
        <phonex>(O=\c:U).:N</phonex>
        <phonex>.:sctype("-O")?(O={g}:N).:N</phonex>
        <group name="O" mark="Onset"/>
    </Stage>
    
    <Stage name="MaxOnset">
        <phonex>(O=\c:U).:O:mdc("2","false")</phonex>
        <group name="O" mark="Onset"/>
    </Stage>

    <Stage name="MarkCoda">
        <phonex>.:N(C=[{-v,laryngeal}{-v,nas,-dorsal}{-v,fri,cor}]:U)</phonex>
        <group name="C" mark="Coda"/>
    </Stage>
    
    <Stage name="MarkOEHSWordMedial">
        <phonex>.:sctype("N|OEHS")(E=.:U)</phonex>
        <group name="E" mark="OEHS"/>
    </Stage>

</SyllabifierDef>

=== cmoyates/phon/syllabifier/src/main/resources/syllabifier/basic/por.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Phon - An open source tool for research in phonology.
 Copyright (C) 2008 The Phon Project, Memorial University <http://phon.ling.mun.ca>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<SyllabifierDef xmlns="https://www.phon.ca/ns/syllabifier"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.phon.ca/ns/syllabifier ../../xml/xsd/syllabifier.xsd"
    name="Portuguese-European" language="por">
    
    <SonorityScale>
        <SonorityClass>
            <phonex>{obs}</phonex>
            <sonorityValue>0</sonorityValue>
        </SonorityClass>
        
        <SonorityClass>
            <phonex>{nas,c}</phonex>
            <sonorityValue>1</sonorityValue>
        </SonorityClass>
        
        <SonorityClass>
            <phonex>{liq}</phonex>
            <sonorityValue>2</sonorityValue>
        </SonorityClass>
        
        <SonorityClass>
            <phonex>\g</phonex>
            <sonorityValue>3</sonorityValue>
        </SonorityClass>
        
        <SonorityClass>
            <phonex>\v</phonex>
            <sonorityValue>4</sonorityValue>
        </SonorityClass>
    </SonorityScale>

    <Stage name="MarkNuclei">
        <phonex>(D=\g\v)</phonex>
        <phonex>(D=\v{g,-stop,-fri,-affricate,-liq})</phonex>
        <phonex>(N=\v)</phonex>
        <group name="D" mark="Diphthong"/>
        <group name="N" mark="Nucleus"/>
    </Stage>

    <Stage name="MarkOnset">
        <phonex>(O=\c:U).:N</phonex>
        <phonex>.:sctype("-O")?(O=\g:N).:N</phonex>
        
        <group name="O" mark="Onset"/>
    </Stage>
    
    <Stage name="MaxOnset">
        <phonex>(O=\c:U).:O:mdc("2","false")</phonex>
        <group name="O" mark="Onset"/>
    </Stage>
    
    <Stage name="MarkCoda">
        <phonex>.:N(C={cor,continuant}:U)</phonex>
       
        <group name="C" mark="Coda"/>
    </Stage>

    <Stage name="MarkInitialCodas">
        <phonex>(C=[\u0283\u0292])[{c,-g}\s\.]</phonex>
        <group name="C" mark="Coda"/>
    </Stage>
    
    <Stage name="MarkOEHS">
        <phonex>(E=\c:U)</phonex>
        <group name="E" mark="OEHS"/>
    </Stage>
    
    <Stage name="Ambisyllabicity">
        <phonex>\v:N(A=\g:N)\v:N</phonex>
        <group name="A" mark="Ambisyllabic"/>
    </Stage>
    
</SyllabifierDef>

=== cmoyates/phon/syllabifier/src/main/resources/syllabifier/basic/ita.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Phon - An open source tool for research in phonology.
 Copyright (C) 2008 The Phon Project, Memorial University <http://phon.ling.mun.ca>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<SyllabifierDef xmlns="https://www.phon.ca/ns/syllabifier"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.phon.ca/ns/syllabifier ../../xml/xsd/syllabifier.xsd"
    name="Italian" language="ita">
    
    <SonorityScale>
        <SonorityClass>
            <phonex>{obs}</phonex>
            <sonorityValue>0</sonorityValue>
        </SonorityClass>
        
        <SonorityClass>
            <phonex>{nas,c}</phonex>
            <sonorityValue>1</sonorityValue>
        </SonorityClass>
        
        <SonorityClass>
            <phonex>{liq}</phonex>
            <sonorityValue>2</sonorityValue>
        </SonorityClass>
        
        <SonorityClass>
            <phonex>\g</phonex>
            <sonorityValue>3</sonorityValue>
        </SonorityClass>
        
        <SonorityClass>
            <phonex>\v</phonex>
            <sonorityValue>4</sonorityValue>
        </SonorityClass>
    </SonorityScale>
    
    <Stage name="MarkNuclei">
        <phonex>(D=\v[{v,high,lax}\g])</phonex>
        <phonex>(N=\v)</phonex>
         
        <group name="D" mark="Diphthong"/>
        <group name="N" mark="Nucleus"/>
    </Stage>
    
    <Stage name="MarkOnset">
        <phonex>(O=\c:U).:N</phonex>
        <phonex>.:sctype("-O")?(O=\g:N).:N</phonex>      
        
        <group name="O" mark="Onset"/>
    </Stage>
    
    <Stage name="MaxOnset">
        <phonex>(O=\c:U).:O:mdc("2","false")</phonex>
        <group name="O" mark="Onset"/>
    </Stage>
    
    <Stage name="MarkCoda">
        <phonex>.:N(C=\c:U)</phonex>
        <group name="C" mark="Coda"/>
    </Stage>
    
    <Stage name="MarkLA">
        <phonex>(LA={strident}:U).:O</phonex>
        <group name="LA" mark="Left Appendix"/>
    </Stage>
    
</SyllabifierDef>

=== cmoyates/phon/syllabifier/src/main/resources/syllabifier/basic/fra-simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Phon - An open source tool for research in phonology.
 Copyright (C) 2008 The Phon Project, Memorial University <http://phon.ling.mun.ca>
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<SyllabifierDef xmlns="https://www.phon.ca/ns/syllabifier"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.phon.ca/ns/syllabifier ../../xml/xsd/syllabifier.xsd"
    name="French (simple)" language="fra-simple">
    
    
    <SonorityScale>
        <SonorityClass>
            <phonex>{obs,-uvular,-fri}</phonex>
            <sonorityValue>0</sonorityValue>
        </SonorityClass>
        <SonorityClass>
            <phonex>{c,nas}</phonex>
            <sonorityValue>1</sonorityValue>
        </SonorityClass>
        <SonorityClass>
            <phonex>[{liq}{uvular,fri}]</phonex>
            <sonorityValue>2</sonorityValue>
        </SonorityClass>
        <SonorityClass>
            <phonex>\g</phonex>
            <sonorityValue>3</sonorityValue>
        </SonorityClass>
        <SonorityClass>
            <phonex>\v</phonex>
            <sonorityValue>4</sonorityValue>
        </SonorityClass>
    </SonorityScale>
    
    <Stage name="MarkNuclei">
        <phonex>(D=\g\v)</phonex>
        <phonex>(D=\v{v,high,lax})</phonex>
        <phonex>(N=\v)</phonex>
        
        <group name="D" mark="Diphthong"/>
        <group name="N" mark="Nucleus"/>
    </Stage>
    
    <Stage name="Final Consonant">
        <phonex>(E=\c:U$)</phonex>
        
        <group name="E" mark="OEHS"/>
    </Stage>
    
    <Stage name="MaxOEHS">
        <phonex>(E=\c:U)\c:E:mdc("2","false")</phonex>
        <group name="E" mark="OEHS"/>
    </Stage>
    
    <Stage name="MarkOnset">
        <phonex>(O=\c:U).:N</phonex>
        <phonex>.:sctype("-O")?(O=\g:N).:N</phonex>
        
        <group name="O" mark="Onset"/>
    </Stage>
    
    <Stage name="MaxOnset">
        <phonex>(O=\c:U)\c:O:mdc("2","false")</phonex>
        <group name="O" mark="Onset"/>
    </Stage>
    
    <Stage name="MarkCoda">
        <phonex>.:N(C=\c:U)</phonex>
        <group name="C" mark="Coda"/>
    </Stage>
    
    <Stage name="MarkLA">
        <phonex>\s?(LA={strident,voiceless}).:O</phonex>
        <phonex>^(LA={strident,voiceless}).:O</phonex>
        <phonex>.:C(LA={strident,voiceless}).:O</phonex>
        
        <group name="LA" mark="Left Appendix"/>
    </Stage>
    
    <Stage name="Fix p[sn]">
        <phonex>\s?(O=p)[sn]:O</phonex>
        <group name="O" mark="Onset"/>
    </Stage>
    
    <Stage name="Fiz gz">
        <phonex>\s?(O=[g\u0261])z:O</phonex>
        <group name="O" mark="Onset"/>
    </Stage>
    
    <Stage name="Make Simple">
        <phonex>(O=.:E+)</phonex>
        <phonex>(L=.:L+)</phonex>
        <phonex>(R=.:R+)</phonex>
        
        <group name="O" mark="Onset"/>
        <group name="L" mark="Onset"/>
        <group name="R" mark="Coda"/>
    </Stage>
    
</SyllabifierDef>
